import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import {
  CheckSquare,
  FileText,
  Lock,
  Plus,
  PlusCircle,
  Target,
  Trash2,
  X,
} from "lucide-react";
import { motion } from "motion/react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocalStorage } from "../hooks/useLocalStorage";

interface Goal {
  id: string;
  name: string;
  goal: number;
  saved: number;
}
interface Habit {
  id: string;
  name: string;
  checked: boolean;
  date: string;
}
interface Expense {
  id: string;
  description: string;
  amount: number;
  date: string;
}

interface GoalsProps {
  isPro: boolean;
  onUpgrade: () => void;
}

const today = () => new Date().toISOString().slice(0, 10);

function generateReportText(
  goals: Goal[],
  expenses: Expense[],
): { content: string; filename: string } {
  const now = new Date();
  const monthName = now.toLocaleString("en-IN", { month: "long" });
  const year = now.getFullYear();
  const currentMonth = now.toISOString().slice(0, 7);

  const monthlyExpenses = expenses
    .filter((e) => e.date.startsWith(currentMonth))
    .reduce((sum, e) => sum + e.amount, 0);

  const SEP1 = "========================================";
  const SEP2 = "----------------------------------------";

  const lines: string[] = [
    SEP1,
    "   SMART LIFE MANAGER — MONTHLY REPORT",
    `   ${monthName} ${year}`,
    SEP1,
    "",
    "SAVINGS GOALS",
    SEP2,
  ];

  if (goals.length === 0) {
    lines.push("  No savings goals found.");
  } else {
    for (const g of goals) {
      const pct =
        g.goal > 0 ? Math.min(100, Math.round((g.saved / g.goal) * 100)) : 0;
      lines.push(`  • ${g.name}`);
      lines.push(`    Target : ₹${g.goal.toLocaleString("en-IN")}`);
      lines.push(`    Saved  : ₹${g.saved.toLocaleString("en-IN")} (${pct}%)`);
      lines.push(
        `    Remaining: ₹${Math.max(0, g.goal - g.saved).toLocaleString("en-IN")}`,
      );
      lines.push("");
    }
  }

  lines.push(`MONTHLY EXPENSES (${monthName} ${year})`);
  lines.push(SEP2);
  lines.push(`  Total Spent: ₹${monthlyExpenses.toLocaleString("en-IN")}`);
  lines.push("");
  lines.push("SUMMARY");
  lines.push(SEP2);
  const totalGoalTarget = goals.reduce((s, g) => s + g.goal, 0);
  const totalSaved = goals.reduce((s, g) => s + g.saved, 0);
  const overallPct =
    totalGoalTarget > 0 ? Math.round((totalSaved / totalGoalTarget) * 100) : 0;
  lines.push(`  Active Goals       : ${goals.length}`);
  lines.push(
    `  Total Goal Target  : ₹${totalGoalTarget.toLocaleString("en-IN")}`,
  );
  lines.push(
    `  Total Saved        : ₹${totalSaved.toLocaleString("en-IN")} (${overallPct}%)`,
  );
  lines.push(
    `  Monthly Expenses   : ₹${monthlyExpenses.toLocaleString("en-IN")}`,
  );
  lines.push("");
  lines.push(
    `  Generated by Smart Life Manager on ${now.toLocaleDateString("en-IN")}`,
  );
  lines.push(SEP1);

  return {
    content: lines.join("\n"),
    filename: `smart-life-report-${currentMonth}.txt`,
  };
}

export default function Goals({ isPro, onUpgrade }: GoalsProps) {
  const [goals, setGoals] = useLocalStorage<Goal[]>("slm_goals", [
    { id: "1", name: "Emergency Fund", goal: 50000, saved: 18000 },
    { id: "2", name: "New Laptop", goal: 60000, saved: 12000 },
    { id: "3", name: "Vacation Fund", goal: 30000, saved: 8500 },
  ]);
  const [habits, setHabits] = useLocalStorage<Habit[]>("slm_habits", [
    { id: "1", name: "Morning Exercise", checked: false, date: today() },
    { id: "2", name: "Read for 30 mins", checked: false, date: today() },
    { id: "3", name: "Track Expenses", checked: false, date: today() },
  ]);
  const [expenses] = useLocalStorage<Expense[]>("slm_expenses", []);

  // Reset habits daily
  // biome-ignore lint/correctness/useExhaustiveDependencies: run once on mount
  useEffect(() => {
    const t = today();
    setHabits((prev) =>
      prev.map((h) => (h.date !== t ? { ...h, checked: false, date: t } : h)),
    );
  }, []);

  const [goalName, setGoalName] = useState("");
  const [goalAmt, setGoalAmt] = useState("");
  const [savedAmt, setSavedAmt] = useState("");
  const [habitName, setHabitName] = useState("");

  // Track which goal has the contribute panel open, keyed by goal id
  const [contributeOpenId, setContributeOpenId] = useState<string | null>(null);
  const [contributeAmt, setContributeAmt] = useState("");

  const addGoal = () => {
    if (!goalName.trim() || !goalAmt || Number(goalAmt) <= 0) {
      toast.error("Enter goal name and amount");
      return;
    }
    // Free user limit: max 1 goal
    if (!isPro && goals.length >= 1) {
      onUpgrade();
      return;
    }
    const newGoal: Goal = {
      id: Date.now().toString(),
      name: goalName.trim(),
      goal: Number(goalAmt),
      saved: Number(savedAmt) || 0,
    };
    setGoals((prev) => [...prev, newGoal]);
    setGoalName("");
    setGoalAmt("");
    setSavedAmt("");
    toast.success("Goal added!");
  };

  const deleteGoal = (id: string) => {
    setGoals((prev) => prev.filter((g) => g.id !== id));
    if (contributeOpenId === id) setContributeOpenId(null);
  };

  const openContribute = (id: string) => {
    setContributeOpenId(id);
    setContributeAmt("");
  };

  const cancelContribute = () => {
    setContributeOpenId(null);
    setContributeAmt("");
  };

  const confirmContribute = (goalId: string) => {
    const amount = Number(contributeAmt);
    if (!amount || amount <= 0) {
      toast.error("Enter a valid amount");
      return;
    }
    setGoals((prev) =>
      prev.map((g) => {
        if (g.id !== goalId) return g;
        const newSaved = Math.min(g.goal, g.saved + amount);
        if (newSaved >= g.goal) {
          toast.success(`🎉 Goal "${g.name}" fully funded!`);
        } else {
          toast.success(
            `₹${amount.toLocaleString("en-IN")} added to ${g.name}`,
          );
        }
        return { ...g, saved: newSaved };
      }),
    );
    setContributeOpenId(null);
    setContributeAmt("");
  };

  const addHabit = () => {
    if (!habitName.trim()) {
      toast.error("Enter habit name");
      return;
    }
    const newHabit: Habit = {
      id: Date.now().toString(),
      name: habitName.trim(),
      checked: false,
      date: today(),
    };
    setHabits((prev) => [...prev, newHabit]);
    setHabitName("");
    toast.success("Habit added!");
  };

  const toggleHabit = (id: string) => {
    setHabits((prev) =>
      prev.map((h) => (h.id === id ? { ...h, checked: !h.checked } : h)),
    );
  };

  const deleteHabit = (id: string) => {
    setHabits((prev) => prev.filter((h) => h.id !== id));
  };

  const handleGenerateReport = () => {
    if (!isPro) return;
    const { content, filename } = generateReportText(goals, expenses);
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded!");
  };

  const completedHabits = habits.filter((h) => h.checked).length;
  const showFreeLimit = !isPro && goals.length >= 1;

  return (
    <div className="space-y-5" data-ocid="goals.section">
      <div className="px-1">
        <h1 className="text-2xl font-bold text-foreground">Goals 🎯</h1>
        <p className="text-muted-foreground text-sm mt-1">
          Track savings goals and build habits
        </p>
      </div>

      {/* Savings Goals */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-card rounded-xl shadow-card border border-border p-5"
      >
        <div className="flex items-center gap-3 mb-4">
          <div className="w-9 h-9 rounded-lg bg-green-50 flex items-center justify-center text-accent">
            <Target size={18} />
          </div>
          <h2 className="font-semibold text-foreground">Savings Goals</h2>
        </div>

        <div className="space-y-2 mb-2">
          <Input
            placeholder="Goal name (e.g. New Laptop)"
            value={goalName}
            onChange={(e) => setGoalName(e.target.value)}
            className="text-sm"
            data-ocid="goal.input"
          />
          <div className="flex gap-2">
            <Input
              placeholder="Target ₹"
              type="number"
              min="0"
              value={goalAmt}
              onChange={(e) => setGoalAmt(e.target.value)}
              className="text-sm"
              data-ocid="goal.amount_input"
            />
            <Input
              placeholder="Saved ₹"
              type="number"
              min="0"
              value={savedAmt}
              onChange={(e) => setSavedAmt(e.target.value)}
              className="text-sm"
              data-ocid="goal.saved_input"
            />
            <Button size="icon" onClick={addGoal} data-ocid="goal.add_button">
              <Plus size={16} />
            </Button>
          </div>
        </div>

        {/* Free plan hint */}
        {showFreeLimit && (
          <p
            className="text-[11px] text-amber-600 bg-amber-50 border border-amber-200 rounded-lg px-3 py-2 mb-3 flex items-center gap-1.5"
            data-ocid="goal.free_limit_hint"
          >
            <Lock size={11} />
            Free plan: 1 goal limit. Upgrade to Pro for unlimited goals.
          </p>
        )}

        <div className="space-y-4">
          {goals.length === 0 && (
            <p
              className="text-center text-muted-foreground text-sm py-3"
              data-ocid="goal.empty_state"
            >
              No goals yet
            </p>
          )}
          {goals.map((goal, i) => {
            const pct = Math.min(
              100,
              Math.round((goal.saved / goal.goal) * 100),
            );
            const isComplete = goal.saved >= goal.goal;
            const isContributing = contributeOpenId === goal.id;

            return (
              <div
                key={goal.id}
                className={`rounded-xl border p-3 transition-colors ${
                  isComplete
                    ? "border-green-300 bg-green-50/60"
                    : "border-border bg-muted/30"
                }`}
                data-ocid={`goal.item.${i + 1}`}
              >
                {/* Goal header row */}
                <div className="flex justify-between items-start mb-1">
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2 flex-wrap">
                      <p className="font-medium text-sm truncate">
                        {goal.name}
                      </p>
                      {isComplete && (
                        <span className="inline-flex items-center gap-1 text-[11px] font-semibold text-green-700 bg-green-100 border border-green-200 rounded-full px-2 py-0.5">
                          🎉 Goal Reached!
                        </span>
                      )}
                    </div>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      ₹{goal.saved.toLocaleString("en-IN")} / ₹
                      {goal.goal.toLocaleString("en-IN")}
                    </p>
                  </div>
                  <div className="flex items-center gap-2 ml-2 shrink-0">
                    <span
                      className={`text-sm font-bold ${
                        isComplete ? "text-green-600" : "text-accent"
                      }`}
                    >
                      {pct}%
                    </span>
                    <button
                      type="button"
                      onClick={() => deleteGoal(goal.id)}
                      className="text-muted-foreground hover:text-destructive transition-colors"
                      data-ocid={`goal.delete_button.${i + 1}`}
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>
                </div>

                {/* Progress bar */}
                <div className="w-full bg-muted rounded-full h-2.5 mb-2">
                  <motion.div
                    className={`h-2.5 rounded-full ${
                      isComplete ? "bg-green-500" : "bg-accent"
                    }`}
                    initial={{ width: 0 }}
                    animate={{ width: `${pct}%` }}
                    transition={{ duration: 0.8, ease: "easeOut" }}
                  />
                </div>

                {/* Contribute button (hidden when complete) */}
                {!isComplete && !isContributing && (
                  <button
                    type="button"
                    onClick={() => openContribute(goal.id)}
                    className="flex items-center gap-1.5 text-xs font-medium text-primary hover:text-primary/80 transition-colors mt-0.5"
                    data-ocid={`goal.contribute_button.${i + 1}`}
                  >
                    <PlusCircle size={13} />
                    Add Savings
                  </button>
                )}

                {/* Inline contribute panel */}
                {isContributing && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: "auto" }}
                    exit={{ opacity: 0, height: 0 }}
                    className="mt-2 pt-2 border-t border-border"
                    data-ocid={`goal.contribute_panel.${i + 1}`}
                  >
                    <p className="text-xs text-muted-foreground mb-2 font-medium">
                      How much are you adding?
                    </p>
                    <div className="flex gap-2">
                      <Input
                        type="number"
                        min="1"
                        placeholder="Amount ₹"
                        value={contributeAmt}
                        onChange={(e) => setContributeAmt(e.target.value)}
                        onKeyDown={(e) => {
                          if (e.key === "Enter") confirmContribute(goal.id);
                          if (e.key === "Escape") cancelContribute();
                        }}
                        className="text-sm h-8"
                        autoFocus
                        data-ocid={`goal.contribute_input.${i + 1}`}
                      />
                      <Button
                        size="sm"
                        onClick={() => confirmContribute(goal.id)}
                        className="h-8 px-3 text-xs"
                        data-ocid={`goal.contribute_confirm.${i + 1}`}
                      >
                        Confirm
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={cancelContribute}
                        className="h-8 px-2"
                        data-ocid={`goal.contribute_cancel.${i + 1}`}
                      >
                        <X size={13} />
                      </Button>
                    </div>
                    {goal.goal - goal.saved > 0 && (
                      <p className="text-[11px] text-muted-foreground mt-1.5">
                        ₹{(goal.goal - goal.saved).toLocaleString("en-IN")}{" "}
                        remaining to reach target
                      </p>
                    )}
                  </motion.div>
                )}
              </div>
            );
          })}
        </div>
      </motion.div>

      {/* Generate Monthly Report */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.05 }}
        className="bg-card rounded-xl shadow-card border border-border p-5"
      >
        <div className="flex items-center gap-3 mb-3">
          <div className="w-9 h-9 rounded-lg bg-blue-50 flex items-center justify-center text-primary">
            <FileText size={18} />
          </div>
          <div>
            <h2 className="font-semibold text-foreground">Monthly Report</h2>
            <p className="text-xs text-muted-foreground">
              Download your goals &amp; expense summary
            </p>
          </div>
        </div>

        <Button
          className="w-full"
          variant={isPro ? "default" : "outline"}
          disabled={!isPro}
          onClick={handleGenerateReport}
          data-ocid="report.generate_button"
          aria-disabled={!isPro}
        >
          {isPro ? (
            <>
              <FileText size={15} className="mr-2" />
              Generate Monthly Report
            </>
          ) : (
            <>
              <Lock size={15} className="mr-2" />
              Generate Monthly Report — Pro Only
            </>
          )}
        </Button>

        {!isPro && (
          <p
            className="text-[11px] text-muted-foreground text-center mt-2"
            data-ocid="report.pro_hint"
          >
            Pro feature — upgrade to unlock
          </p>
        )}
      </motion.div>

      {/* Habit Tracker */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="bg-card rounded-xl shadow-card border border-border p-5"
      >
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-lg bg-blue-50 flex items-center justify-center text-primary">
              <CheckSquare size={18} />
            </div>
            <div>
              <h2 className="font-semibold text-foreground">Habit Tracker</h2>
              <p className="text-xs text-muted-foreground">
                {completedHabits}/{habits.length} done today
              </p>
            </div>
          </div>
          <div className="text-2xl font-bold text-primary">
            {habits.length > 0
              ? Math.round((completedHabits / habits.length) * 100)
              : 0}
            %
          </div>
        </div>

        <div className="flex gap-2 mb-4">
          <Input
            placeholder="New habit name"
            value={habitName}
            onChange={(e) => setHabitName(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && addHabit()}
            className="flex-1 text-sm"
            data-ocid="habit.input"
          />
          <Button size="icon" onClick={addHabit} data-ocid="habit.add_button">
            <Plus size={16} />
          </Button>
        </div>

        <div className="space-y-2">
          {habits.length === 0 && (
            <p
              className="text-center text-muted-foreground text-sm py-3"
              data-ocid="habit.empty_state"
            >
              No habits yet
            </p>
          )}
          {habits.map((habit, i) => (
            <motion.div
              key={habit.id}
              className="flex items-center gap-3 p-3 bg-muted/50 rounded-lg"
              data-ocid={`habit.item.${i + 1}`}
            >
              <Checkbox
                id={`habit-${habit.id}`}
                checked={habit.checked}
                onCheckedChange={() => toggleHabit(habit.id)}
                data-ocid={`habit.checkbox.${i + 1}`}
              />
              <label
                htmlFor={`habit-${habit.id}`}
                className={`flex-1 text-sm cursor-pointer ${habit.checked ? "line-through text-muted-foreground" : ""}`}
              >
                {habit.name}
              </label>
              <button
                type="button"
                onClick={() => deleteHabit(habit.id)}
                className="text-muted-foreground hover:text-destructive transition-colors p-1"
                data-ocid={`habit.delete_button.${i + 1}`}
              >
                <Trash2 size={14} />
              </button>
            </motion.div>
          ))}
        </div>
      </motion.div>
    </div>
  );
}
