/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const NoteEntry = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const UserPreferences = IDL.Record({
  'theme' : IDL.Text,
  'notifications' : IDL.Bool,
});
export const ParsedTransaction = IDL.Record({
  'displayMessage' : IDL.Text,
  'transactionType' : IDL.Text,
  'date' : IDL.Text,
  'merchant' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const ParseResult = IDL.Variant({
  'ok' : ParsedTransaction,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_transformResponse' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'getAllNotesSorted' : IDL.Func([], [IDL.Vec(NoteEntry)], ['query']),
  'getNote' : IDL.Func([IDL.Text], [NoteEntry], ['query']),
  'getNotesByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(NoteEntry)], ['query']),
  'getNotesByTheme' : IDL.Func([IDL.Text], [IDL.Vec(NoteEntry)], ['query']),
  'getOpenAIKeyStatus' : IDL.Func(
      [],
      [IDL.Record({ 'isSet' : IDL.Bool })],
      ['query'],
    ),
  'getPreferences' : IDL.Func([IDL.Text], [UserPreferences], ['query']),
  'noteExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'parseTransaction' : IDL.Func([IDL.Text], [ParseResult], []),
  'saveNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'savePreferences' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(NoteEntry)], ['query']),
  'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
  'updateNotifications' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const NoteEntry = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  const UserPreferences = IDL.Record({
    'theme' : IDL.Text,
    'notifications' : IDL.Bool,
  });
  const ParsedTransaction = IDL.Record({
    'displayMessage' : IDL.Text,
    'transactionType' : IDL.Text,
    'date' : IDL.Text,
    'merchant' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const ParseResult = IDL.Variant({
    'ok' : ParsedTransaction,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    '_transformResponse' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'getAllNotesSorted' : IDL.Func([], [IDL.Vec(NoteEntry)], ['query']),
    'getNote' : IDL.Func([IDL.Text], [NoteEntry], ['query']),
    'getNotesByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(NoteEntry)], ['query']),
    'getNotesByTheme' : IDL.Func([IDL.Text], [IDL.Vec(NoteEntry)], ['query']),
    'getOpenAIKeyStatus' : IDL.Func(
        [],
        [IDL.Record({ 'isSet' : IDL.Bool })],
        ['query'],
      ),
    'getPreferences' : IDL.Func([IDL.Text], [UserPreferences], ['query']),
    'noteExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'parseTransaction' : IDL.Func([IDL.Text], [ParseResult], []),
    'saveNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'savePreferences' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
    'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(NoteEntry)], ['query']),
    'setOpenAIKey' : IDL.Func([IDL.Text], [], []),
    'updateNotifications' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };