/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface NoteEntry { 'title' : string, 'content' : string }
export type ParseResult = { 'ok' : ParsedTransaction } |
  { 'err' : string };
export interface ParsedTransaction {
  'displayMessage' : string,
  'transactionType' : string,
  'date' : string,
  'merchant' : string,
  'category' : string,
  'amount' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserPreferences { 'theme' : string, 'notifications' : boolean }
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_transformResponse' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'deleteNote' : ActorMethod<[string], undefined>,
  'getAllNotesSorted' : ActorMethod<[], Array<NoteEntry>>,
  'getNote' : ActorMethod<[string], NoteEntry>,
  'getNotesByKeyword' : ActorMethod<[string], Array<NoteEntry>>,
  'getNotesByTheme' : ActorMethod<[string], Array<NoteEntry>>,
  'getOpenAIKeyStatus' : ActorMethod<[], { 'isSet' : boolean }>,
  'getPreferences' : ActorMethod<[string], UserPreferences>,
  'noteExists' : ActorMethod<[string], boolean>,
  'parseTransaction' : ActorMethod<[string], ParseResult>,
  'saveNote' : ActorMethod<[string, string, string], undefined>,
  'savePreferences' : ActorMethod<[string, string, boolean], undefined>,
  'searchNotes' : ActorMethod<[string], Array<NoteEntry>>,
  'setOpenAIKey' : ActorMethod<[string], undefined>,
  'updateNotifications' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];