/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NoteEntry {
    title: string;
    content: string;
}
export interface UserPreferences {
    theme: string;
    notifications: boolean;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ParsedTransaction {
    displayMessage: string;
    transactionType: string;
    date: string;
    merchant: string;
    category: string;
    amount: number;
}
export type ParseResult = {
    __kind__: "ok";
    ok: ParsedTransaction;
} | {
    __kind__: "err";
    err: string;
};
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface backendInterface {
    _transformResponse(input: TransformationInput): Promise<TransformationOutput>;
    deleteNote(id: string): Promise<void>;
    getAllNotesSorted(): Promise<Array<NoteEntry>>;
    getNote(id: string): Promise<NoteEntry>;
    getNotesByKeyword(keyword: string): Promise<Array<NoteEntry>>;
    getNotesByTheme(theme: string): Promise<Array<NoteEntry>>;
    getOpenAIKeyStatus(): Promise<{
        isSet: boolean;
    }>;
    getPreferences(userId: string): Promise<UserPreferences>;
    noteExists(id: string): Promise<boolean>;
    parseTransaction(text: string): Promise<ParseResult>;
    saveNote(id: string, title: string, content: string): Promise<void>;
    savePreferences(userId: string, theme: string, notifications: boolean): Promise<void>;
    searchNotes(searchTerm: string): Promise<Array<NoteEntry>>;
    setOpenAIKey(key: string): Promise<void>;
    updateNotifications(userId: string, notifications: boolean): Promise<void>;
}
import type { ParseResult as _ParseResult, ParsedTransaction as _ParsedTransaction } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _transformResponse(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor._transformResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._transformResponse(arg0);
            return result;
        }
    }
    async deleteNote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async getAllNotesSorted(): Promise<Array<NoteEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotesSorted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotesSorted();
            return result;
        }
    }
    async getNote(arg0: string): Promise<NoteEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return result;
        }
    }
    async getNotesByKeyword(arg0: string): Promise<Array<NoteEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByKeyword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByKeyword(arg0);
            return result;
        }
    }
    async getNotesByTheme(arg0: string): Promise<Array<NoteEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByTheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByTheme(arg0);
            return result;
        }
    }
    async getOpenAIKeyStatus(): Promise<{
        isSet: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenAIKeyStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenAIKeyStatus();
            return result;
        }
    }
    async getPreferences(arg0: string): Promise<UserPreferences> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreferences(arg0);
            return result;
        }
    }
    async noteExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.noteExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.noteExists(arg0);
            return result;
        }
    }
    async parseTransaction(arg0: string): Promise<ParseResult> {
        if (this.processError) {
            try {
                const result = await this.actor.parseTransaction(arg0);
                return from_candid_ParseResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.parseTransaction(arg0);
            return from_candid_ParseResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveNote(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveNote(arg0, arg1, arg2);
            return result;
        }
    }
    async savePreferences(arg0: string, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePreferences(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePreferences(arg0, arg1, arg2);
            return result;
        }
    }
    async searchNotes(arg0: string): Promise<Array<NoteEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchNotes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchNotes(arg0);
            return result;
        }
    }
    async setOpenAIKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOpenAIKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOpenAIKey(arg0);
            return result;
        }
    }
    async updateNotifications(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotifications(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotifications(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ParseResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParseResult): ParseResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ParsedTransaction;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ParsedTransaction;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
